### ISSUE TITLE
[Issues #1]Whatevergreen problem [Closed] [Solution: change device-id=12160000]

### ISSUE THREAD

**Issue by khaizr0** [Oshawott-kun/Dell-Inspiron-14-3458-hackintosh-Mojave-opencore-#1]
I'm having a same laptop like you but whatevergreen not working in my laptop and it stuck at throttles=100ms (already set dvmt=64mb) and i have to use older patch kext to make hd5500 working. I need help! Thanks

**Comment by khaizr0** [comment]
I changed device-id=12160000 and it work :D

**Comment by KnoyanMitsu** [comment]
Owh Ok

**Comment by KnoyanMitsu** [comment]
EFI.zip has been update

thank you KhaiZeR0
